### ISSUE TITLE
Configurable payload size

### ISSUE THREAD

**Issue by biemster** [kingyoPiyo/Pico-10BASE-T#2]
Great work, I bought my first rp2040 just to try this out!
While that is in transit, I have a question about the payload size since I can not experiment myself yet. `udp.h` defines a hardcoded payload size of 64 bytes, is this a hard limit or does the code allow larger packets by just increasing this value?

And on a related note, do you have an estimate of the maximum throughput? (I'm planning of streaming raw frames from a MEMS mic with this)

**Comment by kingyoPiyo** [comment]
The size can be increased by changing DEF_UDP_PAYLOAD_SIZE in udp.h. The maximum payload size is 1472Byte.
To improve the effective throughput, it is recommended to increase the payload size and use DMA transfer for data input to PIO. It should be almost up to the theoretical value of 10 Mbps.
See also:
https://github.com/kingyoPiyo/Pico-100BASE-FX

**Comment by biemster** [comment]
Thanks, I'm going to try that out. The mic I have is i2s, but the SDK does not have support for i2s input while arduino-pico and the micropython port do, so I might try to port this to either of these environments. Still quite some work ahead!
