### ISSUE TITLE
Progress on receive support?

### ISSUE THREAD

**Issue by biemster** [kingyoPiyo/Pico-10BASE-T#3]
I've noticed in the README that receive support is being worked on, is there maybe any news on this front?

**Comment by kingyoPiyo** [comment]
I have not made any progress because I have been busy with other things. We will start soon...

**Comment by biemster** [comment]
Is there anything I can do to help?

**Comment by biemster** [comment]
I'm designing a board with this in mind, will the RX pins require the same resistors setup as the TX pins?

**Comment by biemster** [comment]
Great to see your progress in the `rx_dev` branch @kingyoPiyo ! Do you use any passives on the rx lines, maybe something like @cnlohr uses on https://github.com/cnlohr/espthernet?

**Comment by kingyoPiyo** [comment]
Ideally, a differential receiver (e.g., a differential receiver for LVDS) should be used because the received signal is a differential signal. It can also be configured using transistors. We are currently looking for a simplified method. 
I think we can use the method in the URL you introduced.

**Comment by holysnippet** [comment]
[GitHub Doc / Code](https://github.com/holysnippet/pico_eth_doc)
Complete 10BASE-T Compatible library with cheap PHY (resistors & cap) option.
I also implemented lwIP stack. Low CPU usage, full DMA, hardware crc, encoding & ser/des.
This is like Pico W but Ethernet connectivity for nearly nothing. 
@biemster I'm also in DSP SDR radio :p this "lib" that I give for free is part of a secret transceiver project :p

**Comment by kingyoPiyo** [comment]
@holysnippet Thank you for sharing this very nice project!! It was very informative as it completes the main send/receive process in PIO.

**Comment by holysnippet** [comment]
Bonjour, merci pour votre message, content que ça vous plaise !
Le programme du PIO fait effectivement quasiment tout, mais je suis limité à 32 instructions et il manque des choses  (la détection des NLP). Je voulais n'utiliser qu'un seul module PIO, le faire avec les deux serait plus facile !

**Comment by holysnippet** [comment]
Hi, thanks for your message, glad you like it!
The PIO program does indeed do almost everything, but I'm limited to 32 instructions and it's missing some things (NLP detection). I wanted to use only one PIO module, doing it with both would be easier!

**Comment by biemster** [comment]
Wow @holysnippet ! That looks absolutely great! I'm also *very* curious about your secret transceiver now..

**Comment by holysnippet** [comment]
@biemster 
This is a prototype idea. Currently an economical receiver based on a Tayloe mixer. It goes from a few tens of kHz to a little more than 30MHz and has the particularity to be very sensitive. The idea would be to make it (with the Pico Ethernet) a kind of Web SDR like the Kiwi SDR but more economical (and more sensistive) ! But it would not be as powerful. The Kiwi SDR samples the whole HF spectrum. My receiver is I/Q mixer based and has a 17 (true) bit 96kHz ADC.

Unfortunately there is reality and my dreams, the Ethernet is very noisy electrically and I don't think connecting a very sensitive receiver directly to it is a good idea! But I have some ideas :)

**Comment by kingyoPiyo** [comment]
The noise issue is tricky.... Perhaps a good use of fiber optics could solve this problem....the RP2040 is sufficient for only the transmit side of 100BASE-FX, but the receive is tough as it needs to be oversampled with a fast clock.... Anyway, building an SDR receiver would be a very interesting project!
https://github.com/kingyoPiyo/RasPico_SHIBAKI_Board
